{% set version = "0.7.3" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/ef/af/207bc2340f7bde8e5984164e5e25bd63ce783f18d6c5b6c018d4a4887b8f/kececinumbers-0.7.2.tar.gz
  sha256: 6fa84692fa22fe341ecbbcf6797d7d445d48cfc118ec76b32c7cba12af961111
  
channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10
    - numpy
    - matplotlib
    - sympy
    - numpy
    - quaternion    
    # Other runtime dependencies
  build:
    - python >=3.10
    - pip
    - setuptools
    - numpy

test:
  requires:
    - matplotlib
    - scipy
    - sympy
    - numpy
    - quaternion
  imports:
    - kececinumbers
    - matplotlib.pyplot
    - matplotlib.gridspec
    - scipy.fft
    - scipy.signal
    - scipy.stats
    - numpy
    - quaternion

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
