{% set version = "0.5.2" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/db/35/f73021cf34850bb95c16c76ade99b9e6abb71bc7fd0f635904d0f2ca2a0a/kececinumbers-0.5.0.tar.gz
  sha256: 77711a8dc56693d14e067efdea1e9ba34e3db040d13fd24c18c3bb59b5f250bc
  
channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10,<3.12
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy

test:
  imports:
    - kececinumbers

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
