{% set version = "0.5.6" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/c8/20/7f167bb20589b0b96e6d41478824ed795b34ca7fe4011da3a64d71d89d26/kececinumbers-0.5.5.tar.gz
  sha256: 440b1360d54b8abf425e7c0f5a511f52d9e516d0e097987535ca6847fcfe02a8
  
channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10,<3.12
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy

test:
  imports:
    - kececinumbers

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
