{% set version = "0.8.7" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: 
  blake2b-256: 

channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.11
    - numpy
    - matplotlib
    - scipy
    - scikit-learn
    - sympy
    # Other runtime dependencies
  build:
    - python >=3.11
    - pip
    - setuptools
    - numpy
    - matplotlib
    - scipy
    - scikit-learn
    - sympy

test:
  requires:
    - matplotlib
    - scipy
    - scikit-learn
    - sympy
    - numpy
  imports:
    - kececinumbers
    - matplotlib.pyplot
    - matplotlib.gridspec
    - scipy.fft
    - scipy.signal
    - scipy.stats
    - scikit-learn
    - numpy

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: AGPL-3.0-or-later
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
