{% set version = "0.6.2" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/fc/06/221ab185907d62969cc9dd82982362678eb36d4e9166ec4f5df60bf17028/kececinumbers-0.6.2.tar.gz
  sha256: fff398b29131a88cf7c8c001f94c9a086c0df81fe96a82795c4fcf5604c11e27
  
channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10,<3.12
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy

test:
  imports:
    - kececinumbers

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
