{% set version = "0.4.3" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: kececinumbers/
  url:
  sha256:

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10,<3.12
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy

test:
  imports:
    - kececinumbers

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
