{% set version = "0.5.4" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/7b/ca/62aeb65b7e12f02818d317fcc7d2b6c43f67bee4d4dbf5864ef5d90f9ded/kececinumbers-0.5.4.tar.gz
  sha256: 16ceba00275b22861719633b0c47c7765433f82eae5e1aed07a5eab47ffc2377

channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10,<3.12
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy

test:
  imports:
    - kececinumbers

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
