{% set version = "0.7.6" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/9f/8c/58c3070401ec44d297d1303f15dd575bfdcfa01aec0daba29ffbce9c46a3/kececinumbers-0.7.6.tar.gz
  sha256: da851137e884d05aa5dcc5a65e1d4c732f2ba6092ee57d4e761aa37be9817eba

channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10
    - numpy
    - matplotlib
    - quaternion
    - scipy
    - scikit-learn
    - sympy
    # Other runtime dependencies
  build:
    - python >=3.10
    - pip
    - setuptools
    - numpy
    - matplotlib
    - quaternion
    - scipy
    - scikit-learn
    - sympy

test:
  requires:
    - matplotlib
    - scipy
    - scikit-learn
    - sympy
    - numpy
    - quaternion
  imports:
    - kececinumbers
    - matplotlib.pyplot
    - matplotlib.gridspec
    - scipy.fft
    - scipy.signal
    - scipy.stats
    - scikit-learn
    - numpy
    - quaternion

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
