{% set version = "0.4.5" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/63/4a/f222cc6564119edde263ebad1bfec437e019da3603ab9b828303eba37612/kececinumbers-0.4.5.tar.gz
  sha256: 43a3e85489c22be9573e51cf1724a108d36e1d713677c00669e60fcb518fb15e


channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10,<3.12
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy

test:
  imports:
    - kececinumbers

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
