{% set version = "0.7.5" %}

package:
  name: kececinumbers
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/66/e2/fb3a21e2e874e48a74f4d2e6690f575cf73b49f2600fd08e7f006a93535b/kececinumbers-0.7.5.tar.gz
  sha256: 5160d19dfa92a9a6df34b7496f139ddf1b2fb241397f59252f127beaaac8a4a2

channels:
  - conda-forge

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  entry_points:
    - kececinumbers = kececinumbers.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    # Other build tools
  run:
    - python >=3.10
    - numpy
    - matplotlib
    - quaternion
    - scipy
    - sympy
    # Other runtime dependencies
  build:
    - python >=3.10
    - pip
    - setuptools
    - numpy
    - matplotlib
    - quaternion
    - scipy
    - sympy

test:
  requires:
    - matplotlib
    - scipy
    - sympy
    - numpy
    - quaternion
  imports:
    - kececinumbers
    - matplotlib.pyplot
    - matplotlib.gridspec
    - scipy.fft
    - scipy.signal
    - scipy.stats
    - numpy
    - quaternion

about:
  home: https://github.com/WhiteSymmetry/kececinumbers
  license: MIT
  summary: 'Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.'
  description: |
    Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets.
  dev_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_url: https://github.com/WhiteSymmetry/kececinumbers
  doc_source_url: https://github.com/WhiteSymmetry/kececinumbers/blob/main/README.md
