name: Publish New Version and Publish to Zenodo on Release

on:
  release:
    types: [published]

jobs:
  publish-to-zenodo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release archive
        # Proje dosyalarını Zenodo için tek bir zip dosyası haline getiriyoruz.
        # .git ve .github klasörlerini hariç tutuyoruz.
        run: zip -r release.zip . -x ".git/*" -x ".github/*"

      - name: Upload New Version to Zenodo
        # Bu modern action, versiyonlama sürecini tamamen otomatikleştirir.
        uses: madrapps/zenodo-upload@v2.0.0
        with:
          # ÖNEMLİ: Deposition ID yerine Concept ID kullanıyoruz.
          # Bu, action'ın hangi kaydın yeni versiyonunu oluşturacağını bilmesini sağlar.
          concept_id: ${{ secrets.ZENODO_CONCEPT_ID }}
          
          # Zenodo'ya erişim token'ınız.
          zenodo_token: ${{ secrets.ZENODO_TOKEN }}
          
          # Yüklenecek dosyanın adı.
          upload_files: 'release.zip'
          
          # Bu anahtar parametre, action'a yeni bir versiyon oluşturmasını söyler.
          create_new_version: true
          
          # Bu parametre, yükleme tamamlandıktan sonra yeni versiyonu otomatik olarak yayınlar.
          publish: true
