name: Publish New Version to Zenodo on Release

on:
  release:
    types: [published]

jobs:
  publish-to-zenodo:
    runs-on: ubuntu-latest
    steps:
      # 1. Kodu checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Yüklenecek arşivi oluştur
      - name: Create release archive
        run: zip -r release.zip . -x ".git/*" -x ".github/*"

      # 3. Zenodo'ya yükle
      - name: Upload New Version to Zenodo
        uses: ein-sc/action-zenodo-upload@v1 # Bu, en kararlı ve güncel action'dır
        with:
          # ÖNEMLİ: Bu action, Concept ID'yi 'conceptrecid' olarak adlandırır.
          # GitHub Secrets'ınızdaki ZENODO_CONCEPT_ID'yi kullanıyoruz.
          conceptrecid: ${{ secrets.ZENODO_CONCEPT_ID }}
          
          # Zenodo token'ı
          zenodo_token: ${{ secrets.ZENODO_TOKEN }}
          
          # Yüklenecek dosya(lar)
          upload_files: 'release.zip'
          
          # Bu parametre, action'a yeni bir versiyon oluşturup onu yayınlamasını söyler.
          # Bu, 'create_new_version: true' ve 'publish: true' adımlarının birleşimidir.
          publish: true 
          
          # GitHub sürümündeki notları Zenodo'daki "release notes" alanına ekle
          # Bu, dokümantasyonu otomatik olarak senkronize eder.
          notes: ${{ github.event.release.body }}
